//
//  SWOTAnalysis.swift
//  note-ai-app-test
//

import Foundation

// MARK: - ActionItem (embedded in SWOTItem JSONB)

struct ActionItem: Identifiable, Codable, Hashable {
    var id: UUID = UUID()   // not encoded — purely for SwiftUI ForEach stability
    let text: String
    let timeEstimate: String?

    enum CodingKeys: String, CodingKey {
        case text
        case timeEstimate = "time_estimate"
    }
}

// MARK: - SWOTItem

struct SWOTItem: Identifiable, Codable, Hashable {
    var id: UUID
    let point: String
    let detail: String?       // rich 3–5 sentence explanation
    let score: Int            // 0–100
    let category: String
    let actions: [ActionItem]? // micro-actions per point

    enum CodingKeys: String, CodingKey {
        case id, point, detail, score, category, actions
    }

    // Convenience init for legacy rows (no detail/actions)
    init(point: String, score: Int, category: String) {
        self.id = UUID()
        self.point = point
        self.detail = nil
        self.score = score
        self.category = category
        self.actions = nil
    }

    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        // id is generated by AI responses; preserved in JSONB for new analyses
        self.id = (try? container.decode(UUID.self, forKey: .id)) ?? UUID()
        self.point = try container.decode(String.self, forKey: .point)
        self.detail = try? container.decode(String.self, forKey: .detail)
        self.score = try container.decode(Int.self, forKey: .score)
        self.category = try container.decode(String.self, forKey: .category)
        self.actions = try? container.decode([ActionItem].self, forKey: .actions)
    }
}

// MARK: - PersistedActionItem (maps to action_items table)

struct PersistedActionItem: Identifiable, Codable {
    let id: UUID
    let analysisId: UUID
    let swotItemId: UUID
    let quadrant: String      // "strength" | "weakness" | "opportunity" | "threat"
    let text: String
    let timeEstimate: String?
    var isCompleted: Bool
    var completedAt: Date?
    let createdAt: Date

    enum CodingKeys: String, CodingKey {
        case id
        case analysisId   = "analysis_id"
        case swotItemId   = "swot_item_id"
        case quadrant
        case text
        case timeEstimate = "time_estimate"
        case isCompleted  = "is_completed"
        case completedAt  = "completed_at"
        case createdAt    = "created_at"
    }
}

// MARK: - MarketInsights

struct MarketInsights: Codable {
    let marketSize: String?
    let growthRate: String?
    let trendDirection: String?   // "up" | "down" | "stable"
    let keyCompetitors: [String]?

    enum CodingKeys: String, CodingKey {
        case marketSize      = "market_size"
        case growthRate      = "growth_rate"
        case trendDirection  = "trend_direction"
        case keyCompetitors  = "key_competitors"
    }
}

// MARK: - SWOTAnalysis

struct SWOTAnalysis: Identifiable, Codable {
    let id: UUID
    let transcriptionId: UUID

    // Legacy arrays — kept for backward compatibility with old DB rows
    let strengths: [String]
    let weaknesses: [String]
    let opportunities: [String]
    let threats: [String]

    let summary: String?
    let createdAt: Date

    // Rich fields added by migration (nullable — old rows have NULL)
    let strengthItems: [SWOTItem]?
    let weaknessItems: [SWOTItem]?
    let opportunityItems: [SWOTItem]?
    let threatItems: [SWOTItem]?
    let viabilityScore: Int?
    let marketContext: String?
    let marketInsights: MarketInsights?
    let recommendations: [String]?

    enum CodingKeys: String, CodingKey {
        case id
        case transcriptionId  = "transcription_id"
        case strengths
        case weaknesses
        case opportunities
        case threats
        case summary
        case createdAt        = "created_at"
        case strengthItems    = "strength_items"
        case weaknessItems    = "weakness_items"
        case opportunityItems = "opportunity_items"
        case threatItems      = "threat_items"
        case viabilityScore   = "viability_score"
        case marketContext    = "market_context"
        case marketInsights   = "market_insights"
        case recommendations
    }

    // MARK: - Computed helpers (Charts fall back to score=50 for legacy rows)

    var resolvedStrengths: [SWOTItem] {
        strengthItems ?? strengths.map { SWOTItem(point: $0, score: 50, category: "General") }
    }
    var resolvedWeaknesses: [SWOTItem] {
        weaknessItems ?? weaknesses.map { SWOTItem(point: $0, score: 50, category: "General") }
    }
    var resolvedOpportunities: [SWOTItem] {
        opportunityItems ?? opportunities.map { SWOTItem(point: $0, score: 50, category: "General") }
    }
    var resolvedThreats: [SWOTItem] {
        threatItems ?? threats.map { SWOTItem(point: $0, score: 50, category: "General") }
    }

    var avgStrengthScore: Double {
        let items = resolvedStrengths
        guard !items.isEmpty else { return 0 }
        return Double(items.map(\.score).reduce(0, +)) / Double(items.count)
    }
    var avgWeaknessScore: Double {
        let items = resolvedWeaknesses
        guard !items.isEmpty else { return 0 }
        return Double(items.map(\.score).reduce(0, +)) / Double(items.count)
    }
    var avgOpportunityScore: Double {
        let items = resolvedOpportunities
        guard !items.isEmpty else { return 0 }
        return Double(items.map(\.score).reduce(0, +)) / Double(items.count)
    }
    var avgThreatScore: Double {
        let items = resolvedThreats
        guard !items.isEmpty else { return 0 }
        return Double(items.map(\.score).reduce(0, +)) / Double(items.count)
    }
}
